floof/floof/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('menu/', include('menu.urls')),
    path('schedule/', include('schedule.urls'))
]

floof/meals/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.meal_index,
        name='meals'
    ),
    path(
        '<int:id>',
        views.meal_view,
        name='meal_view'
    ),
    path(
        'add',
        views.meal_add,
        name='meal_add'
    ),
    path(
        'edit/<int:id>',
        views.meal_edit,
        name='meal_edit'
    ),
    path(
        'delete/<int:id>',
        views.meal_delete,
        name='meal_delete'
    ),
    path(
        'ingredients',
        views.ingredient_index,
        name='ingredients'),
    path(
        'ingredients/<int:id>',
        views.ingredient_view,
        name='ingredient_view'
    ),
    path(
        'ingredients/add',
        views.ingredient_add,
        name='ingredient_add'
    ),
    path(
        'ingredients/edit/<int:id>',
        views.ingredient_edit,
        name='ingredient_edit'
    ),
    path(
        'ingredients/delete/<int:id>',
        views.ingredient_delete,
        name='ingredient_delete'
    ),
    path(
        'mealingredients/add/<int:meal_id>',
        views.mealingredient_add,
        name='mealingredient_add'
    ),
    path(
        'mealingredients/edit/<int:id>',
        views.mealingredient_edit,
        name='mealingredient_edit'
    ),
    path(
        'mealingredients/delete/<int:id>',
        views.mealingredient_delete,
        name='mealingredient_delete'
    )
]

floof/menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(
        'meals',
        views.meal_index,
        name='meals'
    ),
    path(
        'meals/<int:id>',
        views.meal_view,
        name='meal_view'
    ),
    path(
        'meals/add',
        views.meal_add,
        name='meal_add'
    ),
    path(
        'meals/edit/<int:id>',
        views.meal_edit,
        name='meal_edit'
    ),
    path(
        'meals/delete/<int:id>',
        views.meal_delete,
        name='meal_delete'
    ),
    path(
        'ingredients',
        views.ingredient_index,
        name='ingredients'),
    path(
        'ingredients/<int:id>',
        views.ingredient_view,
        name='ingredient_view'
    ),
    path(
        'ingredients/add',
        views.ingredient_add,
        name='ingredient_add'
    ),
    path(
        'ingredients/edit/<int:id>',
        views.ingredient_edit,
        name='ingredient_edit'
    ),
    path(
        'ingredients/delete/<int:id>',
        views.ingredient_delete,
        name='ingredient_delete'
    ),
    path(
        'mealingredients/add/<int:meal_id>',
        views.mealingredient_add,
        name='mealingredient_add'
    ),
    path(
        'mealingredients/edit/<int:id>',
        views.mealingredient_edit,
        name='mealingredient_edit'
    ),
    path(
        'mealingredients/delete/<int:id>',
        views.mealingredient_delete,
        name='mealingredient_delete'
    )
]

floof/menu/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from schedule.models import SlotType


class Ingredient(models.Model):
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=64)
    servings = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    url = models.URLField(blank=True, null=True)

    objects = models.Manager()

    def save(self, *args, **kwargs):
        if self.pk:
            prev_price = Ingredient.objects.get(pk=self.pk).price
            if prev_price != self.price:
                PriceHistory.objects.create(
                    ingredient=self,
                    prev_price=prev_price,
                    new_price=self.price
                )
        super().save(*args, **kwargs)

    def unit_cost(self):
        return self.price / self.servings

    def __str__(self):
        return f'{self.name}'


class PriceHistory(models.Model):
    class Meta:
        verbose_name_plural = 'price history'

    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    prev_price = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    new_price = models.DecimalField(max_digits=4, decimal_places=2, default=0)
    changed_at = models.DateTimeField(auto_now=True)

    def formatted_change_date(self):
        return self.changed_at.strftime('%B %d, %Y %H:%M:%S')

    def __str__(self):
        return f"""{self.ingredient} from {self.prev_price} to {self.new_price}
        at {self.formatted_change_date()}"""


class Meal(models.Model):
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=128)
    slot_type = models.ForeignKey(SlotType, on_delete=models.CASCADE)
    healthiness = models.IntegerField(
        default=1,
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    ingredients = models.ManyToManyField(Ingredient, through='MealIngredient')

    objects = models.Manager()

    def cost(self):
        return round(sum(item.cost() for item in self.mealingredient_set.all()), 2)

    def all_ingredients(self):
        return ', '.join(str(v) for v in self.mealingredient_set.all())

    def __str__(self):
        return f'{self.name} : {self.all_ingredients()} = {self.cost():.2f}€'


class MealIngredient(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    objects = models.Manager()

    def cost(self):
        return round(self.ingredient.unit_cost() * self.quantity, 2)

    def __str__(self):
        return f'{self.quantity}x {self.ingredient} @{self.cost():.2f}€'

floof/meals/forms.py
from django.forms import ModelForm, NumberInput, Select, TextInput
from meals.models import Ingredient, Meal, MealIngredient


class MealForm(ModelForm):
    class Meta:
        model = Meal
        fields = ['name', 'healthiness']
        widgets = {
            'name': TextInput(attrs={'type': 'text'}),
            'healthiness': NumberInput(attrs={'type': 'number', 'step': 1, 'min': 1, 'max': 5})
        }


class IngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={'type': 'text'}),
            'servings': NumberInput(attrs={'type': 'number', 'step': 1}),
            'price': NumberInput(attrs={'type': 'number', 'step': 0.01}),
            'url': TextInput(attrs={'type': 'url'})
        }


class MealIngredientForm(ModelForm):
    class Meta:
        model = MealIngredient
        fields = '__all__'
        widgets = {
            'meal': Select(attrs={'required': 'true'}),
            'ingredient': Select(attrs={'required': 'true'}),
            'quantity': NumberInput(attrs={'type': 'number', 'step': 1})
        }

floof/menu/forms.py
from django.forms import ModelForm, NumberInput, Select, TextInput
from menu.models import Ingredient, Meal, MealIngredient


class MealForm(ModelForm):
    class Meta:
        model = Meal
        fields = ['name', 'slot_type', 'healthiness']
        labels = {'slot_type': 'Type'}
        widgets = {
            'name': TextInput(attrs={'type': 'text'}),
            'slot_type': Select(attrs={'required': 'true'}),
            'healthiness': NumberInput(attrs={'type': 'number', 'step': 1, 'min': 1, 'max': 5})
        }


class IngredientForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={'type': 'text'}),
            'servings': NumberInput(attrs={'type': 'number', 'step': 1}),
            'price': NumberInput(attrs={'type': 'number', 'step': 0.01}),
            'url': TextInput(attrs={'type': 'url'})
        }


class MealIngredientForm(ModelForm):
    class Meta:
        model = MealIngredient
        fields = '__all__'
        widgets = {
            'meal': Select(attrs={'required': 'true'}),
            'ingredient': Select(attrs={'required': 'true'}),
            'quantity': NumberInput(attrs={'type': 'number', 'step': 1})
        }

floof/meals/views.py
from django.shortcuts import get_object_or_404, render, redirect
from meals.forms import IngredientForm, MealForm, MealIngredientForm
from meals.models import Ingredient, Meal, MealIngredient

def meal_index(request):
    return render(
        request,
        'meals.html',
        {
            'meals': Meal.objects.all()
        }
    )

def ingredient_index(request):
    return render(
        request,
        'ingredients.html',
        {
            'ingredients': Ingredient.objects.all()
        }
    )

def meal_view(request, id):
    meal = get_object_or_404(Meal, pk=id)

    return render(
        request,
        'meal_view.html',
        {
            'meal': meal
        }
    )

def ingredient_view(request, id):
    ingredient = get_object_or_404(Ingredient, pk=id)

    return render(
        request,
        'ingredient_view.html',
        {
            'ingredient': ingredient
        }
    )

def meal_add(request):
    if request.method == 'POST':
        form = MealForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('meals')
    else:
        form = MealForm()

    return render(request, 'meal_add.html', {'form': form})

def ingredient_add(request):
    if request.method == 'POST':
        form = IngredientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ingredients')
    else:
        form = IngredientForm()

    return render(request, 'ingredient_add.html', {'form': form})

def mealingredient_add(request, meal_id):
    if request.method == 'POST':
        form = MealIngredientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('meal_view', id=meal_id)
    else:
        form = MealIngredientForm(initial={'meal': meal_id})

    return render(request, 'mealingredient_add.html', {'form': form, 'meal_id': meal_id})

def meal_edit(request, id):
    meal = get_object_or_404(Meal, pk=id)
    is_callback = request.GET.get('ref') == 'callback'

    if request.method == 'POST':
        form = MealForm(request.POST, instance=meal)
        if form.is_valid():
            form.save()
            return redirect('meal_view', id=id) if is_callback else redirect('meals')
    else:
        form = MealForm(instance=meal)

    context = {'form': form, 'callback': id} if is_callback else {'form': form}
    return render(request, 'meal_edit.html', context)

def ingredient_edit(request, id):
    ingredient = get_object_or_404(Ingredient, pk=id)
    is_callback = request.GET.get('ref') == 'callback'

    if request.method == 'POST':
        form = IngredientForm(request.POST, instance=ingredient)
        if form.is_valid():
            form.save()
            return redirect('ingredient_view', id=id) if is_callback else redirect('ingredients')
    else:
        form = IngredientForm(instance=ingredient)

    context = {'form': form, 'callback': id} if is_callback else {'form': form}
    return render(request, 'ingredient_edit.html', context)

def mealingredient_edit(request, id):
    mealingredient = get_object_or_404(MealIngredient, pk=id)
    meal_id = mealingredient.meal.id

    if request.method == 'POST':
        form = MealIngredientForm(request.POST, instance=mealingredient)
        if form.is_valid():
            form.save()
            return redirect('meal_view', id=meal_id)
    else:
        form = MealIngredientForm(instance=mealingredient)

    return render(request, 'mealingredient_edit.html', {'form': form, 'meal_id': meal_id})

def meal_delete(request, id):
    meal = get_object_or_404(Meal, pk=id)
    meal.delete()

    return redirect(meal_index)

def ingredient_delete(request, id):
    ingredient = get_object_or_404(Ingredient, pk=id)
    ingredient.delete()

    return redirect(ingredient_index)

def mealingredient_delete(request, id):
    mealingredient = get_object_or_404(MealIngredient, pk=id)
    mealingredient.delete()

    return redirect(meal_view, id=mealingredient.meal.id)

floof/menu/views.py
from django.shortcuts import get_object_or_404, render, redirect
from menu.forms import IngredientForm, MealForm, MealIngredientForm
from menu.models import Ingredient, Meal, MealIngredient

def meal_index(request):
    return render(
        request,
        'meals.html',
        {
            'meals': Meal.objects.all()
        }
    )

def ingredient_index(request):
    return render(
        request,
        'ingredients.html',
        {
            'ingredients': Ingredient.objects.all()
        }
    )

def meal_view(request, id):
    meal = get_object_or_404(Meal, pk=id)

    return render(
        request,
        'meal_view.html',
        {
            'meal': meal
        }
    )

def ingredient_view(request, id):
    ingredient = get_object_or_404(Ingredient, pk=id)

    return render(
        request,
        'ingredient_view.html',
        {
            'ingredient': ingredient
        }
    )

def meal_add(request):
    if request.method == 'POST':
        form = MealForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('meals')
    else:
        form = MealForm()

    return render(request, 'meal_add.html', {'form': form})

def ingredient_add(request):
    if request.method == 'POST':
        form = IngredientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ingredients')
    else:
        form = IngredientForm()

    return render(request, 'ingredient_add.html', {'form': form})

def mealingredient_add(request, meal_id):
    if request.method == 'POST':
        form = MealIngredientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('meal_view', id=meal_id)
    else:
        form = MealIngredientForm(initial={'meal': meal_id})

    return render(request, 'mealingredient_add.html', {'form': form, 'meal_id': meal_id})

def meal_edit(request, id):
    meal = get_object_or_404(Meal, pk=id)
    is_callback = request.GET.get('ref') == 'callback'

    if request.method == 'POST':
        form = MealForm(request.POST, instance=meal)
        if form.is_valid():
            form.save()
            return redirect('meal_view', id=id) if is_callback else redirect('meals')
    else:
        form = MealForm(instance=meal)

    context = {'form': form, 'callback': id} if is_callback else {'form': form}
    return render(request, 'meal_edit.html', context)

def ingredient_edit(request, id):
    ingredient = get_object_or_404(Ingredient, pk=id)
    is_callback = request.GET.get('ref') == 'callback'

    if request.method == 'POST':
        form = IngredientForm(request.POST, instance=ingredient)
        if form.is_valid():
            form.save()
            return redirect('ingredient_view', id=id) if is_callback else redirect('ingredients')
    else:
        form = IngredientForm(instance=ingredient)

    context = {'form': form, 'callback': id} if is_callback else {'form': form}
    return render(request, 'ingredient_edit.html', context)

def mealingredient_edit(request, id):
    mealingredient = get_object_or_404(MealIngredient, pk=id)
    meal_id = mealingredient.meal.id

    if request.method == 'POST':
        form = MealIngredientForm(request.POST, instance=mealingredient)
        if form.is_valid():
            form.save()
            return redirect('meal_view', id=meal_id)
    else:
        form = MealIngredientForm(instance=mealingredient)

    return render(request, 'mealingredient_edit.html', {'form': form, 'meal_id': meal_id})

def meal_delete(request, id):
    meal = get_object_or_404(Meal, pk=id)
    meal.delete()

    return redirect(meal_index)

def ingredient_delete(request, id):
    ingredient = get_object_or_404(Ingredient, pk=id)
    ingredient.delete()

    return redirect(ingredient_index)

def mealingredient_delete(request, id):
    mealingredient = get_object_or_404(MealIngredient, pk=id)
    mealingredient.delete()

    return redirect(meal_view, id=mealingredient.meal.id)

floof/menu/templates/ingredient_add.html
{% extends 'base.html' %}
{% block title %}Add ingredient{% endblock %}
{% block content %}
        <a href="{% url 'ingredients' %}">Back to ingredients</a>
        <h1>Add ingredient</h1>
        <form method="post">
            {% csrf_token %}
            <table>
                {{form}}
            </table>
            <button type="submit">Submit</button>
        </form>
{% endblock %}

floof/menu/templates/ingredient_edit.html
{% extends 'base.html' %}
{% block title %}Edit ingredient{% endblock %}
{% block content %}
        {% if callback %}
        <a href="{% url 'ingredient_view' id=callback %}">Back to ingredient</a>
        {% else %}
        <a href="{% url 'ingredients' %}">Back to ingredients</a>
        {% endif %}
        <h1>Edit ingredient</h1>
        <form method="post">
            {% csrf_token %}
            <table>
                {{form}}
            </table>
            <button type="submit">Submit</button>
        </form>
{% endblock %}

floof/menu/templates/ingredient_view.html
{% extends 'base.html' %}
{% block title %}Edit ingredient{% endblock %}
{% block content %}
        <a href="{% url 'ingredients' %}">Back to ingredients</a>
        <h1>
                View ingredient (
                <a href="{% url 'ingredient_edit' id=ingredient.id %}?ref=callback">Edit</a>
                |
                <a
                        href="{% url 'ingredient_delete' id=ingredient.id %}?ref=callback"
                        onclick="return confirm('Are you sure?')"
                >
                        Delete
                </a>
                )
        </h1>
        <p>
                <div><b>Name: </b>{{ingredient.name}}</div>
                <div><b>Servings: </b>{{ingredient.servings}}</div>
                <div><b>Price: </b>{{ingredient.price}}</div>
                <div><b>URL: </b>
        {% if ingredient.url %}
                        <a href="{{ingredient.url}}" target="_blank">{{ingredient.url}}</a>
        {% else %}
                        None
        {% endif %}
                </div>
        </p>
        {% if ingredient.pricehistory_set.count > 0 %}
        <h1>Price history</h1>
        <table>
                <tr>
                        <th>Previous price</th>
                        <th>New price</th>
                        <th>Modified at</th>
                </tr>
                {% for modification in ingredient.pricehistory_set.all %}
                <tr>
                        <td class="numeric">{{modification.prev_price}}</td>
                        <td class="numeric">{{modification.new_price}}</td>
                        <td>{{modification.formatted_change_date}}</td>
                </tr>
                {% endfor %}
        </table>
        {% endif %}
{% endblock %}

floof/menu/templates/ingredients.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Welcome!{% endblock %}
{% block content %}
        <a href="{% url 'index' %}">Back home</a>
        <h2>Ingredients <a href="{% url 'ingredient_add' %}">(Add)</a></h2>
        <table>
                <tr>
                        <th>Name</th>
                        <th>Servings</th>
                        <th>Price</th>
                        <th>URL</th>
                        <th>Edit</th>
                        <th>Delete</th>
                </tr>
        {% for ingredient in ingredients %}
                <tr>
                        <td><a href="{% url 'ingredient_view' id=ingredient.id %}">{{ingredient.name}}</a></td>
                        <td class="numeric">{{ingredient.servings}}</td>
                        <td class="numeric">{{ingredient.price}}</td>
                        <td>
                        {% if ingredient.url %}
                                <a href="{{ingredient.url}}" target="_blank">External link</a>
                        {% else %}
                                No external link
                        {% endif %}
                        </td>
                        <td><a href="{% url 'ingredient_edit' id=ingredient.id %}">Edit</a></td>
                        <td>
                                <a
                                        href="{% url 'ingredient_delete' id=ingredient.id %}"
                                        onclick="return confirm('Are you sure?')"
                                >
                                        Delete
                                </a>
                        </td>
                </tr>
        {% endfor %}
        </table>
{% endblock %}

floof/menu/templates/meal_add.html
{% extends 'base.html' %}
{% block title %}Add meal{% endblock %}
{% block content %}
        <a href="{% url 'meals' %}">Back to meals</a>
        <h1>Add meal</h1>
        <form method="post">
            {% csrf_token %}
            <table>
                {{form}}
            </table>
            <button type="submit">Submit</button>
        </form>
{% endblock %}

floof/menu/templates/meal_edit.html
{% extends 'base.html' %}
{% block title %}Edit meal{% endblock %}
{% block content %}
        {% if callback %}
        <a href="{% url 'meal_view' id=callback %}">Back to meal</a>
        {% else %}
        <a href="{% url 'meals' %}">Back to meals</a>
        {% endif %}
        <h1>Edit meal</h1>
        <form method="post">
            {% csrf_token %}
            <table>
                {{form}}
            </table>
            <button type="submit">Submit</button>
        </form>
{% endblock %}

floof/menu/templates/meal_view.html
{% extends 'base.html' %}
{% block title %}Edit meal{% endblock %}
{% block content %}
        <a href="{% url 'meals' %}">Back to meals</a>
        <h1>
                View meal (
                <a href="{% url 'meal_edit' id=meal.id %}?ref=callback">Edit</a>
                |
                <a
                        href="{% url 'meal_delete' id=meal.id %}?ref=callback"
                        onclick="return confirm('Are you sure?')"
                >
                        Delete
                </a>
                )
        </h1>
        <p>
                <div><b>Name: </b>{{meal.name}}</div>
                <div><b>Type: </b>{{meal.slot_type}}</div>
                <div><b>Healthiness: </b>{{meal.healthiness}}/5</div>
                <div><b>Cost: </b>{{meal.cost}}€</div>
        </p>
        <h1>Ingredients <a href="{% url 'mealingredient_add' meal_id=meal.id %}">(Add)</a></h1>
        {% if meal.mealingredient_set.count > 0 %}
        <table>
                <tr>
                        <th>Ingredient</th>
                        <th>Quantity</th>
                        <th>Cost</th>
                        <th>Edit</th>
                        <th>Delete</th>
                </tr>
                {% for component in meal.mealingredient_set.all %}
                <tr>
                        <td>{{component.ingredient.name}}</td>
                        <td class="numeric">{{component.quantity}}</td>
                        <td class="numeric">{{component.cost}}€</td>
                        <td><a href="{% url 'mealingredient_edit' id=component.id %}">Edit</a></td>
                        <td>
                                <a
                                        href="{% url 'mealingredient_delete' id=component.id %}"
                                        onclick="return confirm('Are you sure?')"
                                >
                                        Delete
                                </a>
                        </td>
                </tr>
                {% endfor %}
        </table>
        {% endif %}
{% endblock %}

floof/menu/templates/mealingredient_add.html
{% extends 'base.html' %}
{% block title %}Add meal ingredient{% endblock %}
{% block content %}
        <a href="{% url 'meal_view' id=meal_id %}">Back to meal</a>
        <h1>Add meal ingredient</h1>
        <form method="post">
            {% csrf_token %}
            <table>
                {{form}}
            </table>
            <button type="submit">Submit</button>
        </form>
{% endblock %}

floof/menu/templates/mealingredient_edit.html
{% extends 'base.html' %}
{% block title %}Edit meal{% endblock %}
{% block content %}
        <a href="{% url 'meal_view' id=meal_id %}">Back to meal</a>
        <h1>Edit meal ingredients</h1>
        <form method="post">
            {% csrf_token %}
            <table>
                {{form}}
            </table>
            <button type="submit">Submit</button>
        </form>
{% endblock %}

floof/menu/templates/meals.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Welcome!{% endblock %}
{% block content %}
        <a href="{% url 'index' %}">Back home</a>
        <h2>Meals <a href="{% url 'meal_add' %}">(Add)</a></h2>
        <table>
                <tr>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Ingredients</th>
                        <th>Cost</th>
                        <th>Healthiness</th>
                        <th>Edit</th>
                        <th>Delete</th>
                </tr>
        {% for meal in meals %}
                <tr>
                        <td><a href="{% url 'meal_view' id=meal.id %}">{{meal.name}}</a></td>
                        <td>{{meal.slot_type}}</td>
                        <td>{{meal.all_ingredients}}</td>
                        <td>{{meal.cost}}</td>
                        <td>{{meal.healthiness}}/5</td>
                        <td><a href="{% url 'meal_edit' id=meal.id %}">Edit</a></td>
                        <td>
                                <a
                                        href="{% url 'meal_delete' id=meal.id %}"
                                        onclick="return confirm('Are you sure?')"
                                >
                                        Delete
                                </a>
                        </td>
                </tr>
        {% endfor %}
        </table>
{% endblock %}